 version: '3.8'
 
 services:
     postgres:
        container_name: iad_sbras_postgres
        image: leujo/postgres:latest
        restart: always
        ports:
          - 5432:5432
        environment:
          DATABASE_HOST: "127.0.0.1"
          POSTGRES_USER: "iadsbras"
          POSTGRES_PASSWORD: "p@ssw0rd"
          POSTGRES_DB: "IadSbrasDB"
            
     postgresgui:
       container_name: iad_sbras_postgresgui
       image: dpage/pgadmin4:latest
       restart: always
       environment:
         PGADMIN_DEFAULT_EMAIL: "pgadmin@iadsbras.ru"
         PGADMIN_DEFAULT_PASSWORD: "p@ssw0rd"
       ports:
         - 5050:80
       depends_on:
         - postgres
       volumes:
         - ./etc/pgadmin/servers.json:/pgadmin4/servers.json
