 version: '3.8'
 
 services:
     postgres:
        container_name: some-postgres
        image: postgres:latest
        restart: always
        ports:
          - 5432:5432
        environment:
          DATABASE_HOST: "127.0.0.1"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "admin"
          POSTGRES_DB: "IadSbran"