version: '3.8'

services:
  icswebapp:
    container_name: iad-sbras
    image: leujo/iad-sbras
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/iad-sbras.ru.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/iad-sbras.ru.key
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
