 version: '3.8'
 
 services:
     postgres:
        container_name: iad_sbran_postgres
        image: postgres:latest
        restart: always
        ports:
          - 5432:5432
        environment:
          DATABASE_HOST: "127.0.0.1"
          POSTGRES_USER: "scientist"
          POSTGRES_PASSWORD: "P@ssw0rd"
          POSTGRES_DB: "IadSbran"
        volumes:
          - ../DockerData/postgres/data:/var/lib/postgresql/data